### ISSUE TITLE
some wrong formula in there.

### ISSUE THREAD

**Issue by chicha1986** [travissluka/geoKdTree#4]
Hello I appreciate you demo this program to run that.
but I run your code, and it will show wrong result.
As I decode it, you want to trans spherical location to xyz location.
but it will take short distance by down to land. because it is the minimal distance in there.
So I think it have to modify some of that.
Thank you.

**Comment by travissluka** [comment]
thank you for looking at this. I'm not entirely clear what you think the problem is though.
By design, the shortest Euclidean (through the earth) distance is used because it is faster and close enough for most purposes. If `exact=.true.` is set, then the proper "great circle distance" is used.

**Comment by chicha1986** [comment]
Thank you for your reply. I am interesting for the result, for example I gave 0.25 degree with global. 
So  lons(i)=0.+float(i-1)*(360./1440.)  i=1,1440
And lats(j)=-90.+float(j-1)*(180./720.)  j=1,721
and try to find nearst target_lat&lon is (20N, 120E) 
the result should be 19.75-20.25 and 119.75-120.25, but the result is wrong.
so I think it have something in the code should be modify.

**Comment by travissluka** [comment]
I am not able to reproduce your problem. Using the following test program I do get the expected output.

```fortran
program test
    use kdtree

    type(kd_root) :: kd
    integer, parameter :: s_num = 9
    integer :: r_points(s_num), r_num, i, j, n
    real :: lats(1440*721), lons(1440*721), r_dist(s_num)

    do i=1,1440
        do j=1,721
            n=(i-1)*721 + j
            lats(n) = -90.0 + (j-1.0)*(180.0/720.0)
            lons(n) = (i-1.0)*(360.0/1440.0)
        end do
    end do

    call kd_init(kd, lons, lats)
    call kd_search_nnearest(kd, 120.0, 20.0, s_num, r_points, r_dist, r_num, .false.)

    do i=1,s_num
        print *, i, lons(r_points(i)), lats(r_points(i)), r_dist(i)
    end do
end program test
```

output (index, lon, lat, distance):

```bash
           1   120.250000       19.7500000       38162.2070    
           2   120.250000       20.2500000       38133.7969    
           3   119.750000       19.7500000       38162.2070    
           4   119.750000       20.2500000       38133.7969    
           5   119.750000       20.0000000       26123.4727    
           6   120.000000       20.2500000       27800.0195    
           7   120.000000       19.7500000       27800.0195    
           8   120.250000       20.0000000       26123.4727    
           9   120.000000       20.0000000       0.00000000  
```

**Comment by chicha1986** [comment]
I got problem, the problem is I use lat &lon in each dimension.
 so that will get error in there. I apologize with that, thank you for your feedback.
